### ISSUE TITLE
bugs in osx EI capitan

### ISSUE THREAD

**Issue by ZYecho** [xdanaux/moderncv#26]
when i use xelatex complies  templatex-zh.tex， i find it was ok to use classic and oldstyle  but failed when I used banking and casual style. The error was reported as below.

`/usr/local/texlive/2015/texmf-dist/tex/latex/fontawesome/fontawesome.sty:27: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! [\newfontfamily{\FA}{FontAwesome}]`

Is there any bugs? May be something wrong with fontawesome?

**Comment by xdanaux** [comment]
Looks like an issue with fontawesome. Can you update to the latest release of fontawesome and confirm you still have an issue? If you do, please attach the full compilation log.

**Comment by ghost** [comment]
Same issue but fixed eventually. It takes me a few hours... QAQ

If you have installed the `fontawesome` package, just install `FontAwesome.otf` to system's `Font Book.app`. The path of this file is `/usr/local/texlive/.../texmf-dist/fonts/opentype/public/fontawesome/FontAwesome.otf`.

If you try to compile with `pdflatex`, it will return 0 error. So this bug may be caused by the way  XeLaTeX find fonts. Maybe [this issue](https://github.com/xdanaux/fontawesome-latex/issues/9) describes the same problem.

PS: I would appreciate it if you could port this CV template to TeXmacs...

**Comment by ZYecho** [comment]
thanks a lot.
